const selectOptions = {
  dist_array: [
    "Any distance",
    "2 miles",
    "5 miles",
    "10 miles",
    "25 miles",
    "50 miles",
    "100 miles",
  ],

  cat_array: [
    "Any category",
    "Art & Culture",
    "Career & Business",
    "Community & Environment",
    "Dancing",
    "Games",
    "Health & Wellbeing",
    "Hobbies & Passions",
    "Identity & Language",
    "Movements & Politics",
    "Music",
    "Parents & Family",
    "Pets & Animals",
    "Religion & Spirituality",
    "Science & Education",
    "Social Activities",
    "Sports & Fitness",
    "Support & Coaching",
    "Technology",
    "Travel & Outdoor",
    "Writing",
  ],
  type_array: ["Any type", "Online", "In person"],
  day_array: [
    "Any day",
    "Starting soon",
    "Today",
    "Tomorrow",
    "This week",
    "This weekend",
    "Next week",
    "Custom",
  ],
  sort_by: ["Sort by: Date", " Sort by: Relavence"],
};
export default selectOptions;